project_name: nothelp
builds:
  - main: ./
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - -s -w
    flags:
      - -trimpath
      - -buildvcs=false

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
