name: release

on:
  push:
    branches: [main]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master
        with:
          go-version: 1.24

      - name: Make
        run: make

      - name: Release
        uses: go-semantic-release/action@v1.23
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          changelog-file: true
          changelog-generator-opt: "emojis=true"
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
